# Pytorch Tecnsor

### Tensor 생성

In [ ]:
# !pip3 install torch torchvision

In [ ]:
import torch

t1 = torch.tensor([1, 2, 3], dtype=torch.float)
print(t1)
print(t1.dtype)
print(t1.shape)                             # shape은 기본적으로 .size()와 같다.
print(t1.size())                            # size() 차원과 행, 열의 개수
print('t1의 차원 수: ', t1.dim())            # 텐서의 차원 수
print(t1.device)                            # 텐서가 저장된 장치 확인
print(t1.requires_grad)                     # 텐서가 필요한 연산을 기록할지 여부
print('--------------------------------')

t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t2)
print(t2.dtype)
print(t2.shape)
print(t2.size())
print('t2의 차원 수: ', t2.dim())
print(t2.device)
print(t2.requires_grad)
print('--------------------------------')
t3 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(t3)
print(t3.dtype)
print(t3.shape)
print(t3.size())
print('t3의 차원 수: ', t3.dim())
print(t3.device)
print(t3.requires_grad)
print('--------------------------------')

tensor([1., 2., 3.])
torch.float32
torch.Size([3])
torch.Size([3])
t1의 차원 수:  1
cpu
False
--------------------------------
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])
torch.Size([2, 3])
t2의 차원 수:  2
cpu
False
--------------------------------
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.int64
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
t3의 차원 수:  3
cpu
False
--------------------------------


In [22]:
# 0 또는 1 tensor 생성
print(torch.ones(2, 3), '\n')    # 2행 3열의 1로 채워진 텐서, 자료형 float32
print(torch.zeros(2, 3), '\n')   # 2행 3열의 0으로 채워진 텐서, 자료형 float32

# 랜덤 텐서 생성
print(torch.randn(2, 3), '\n')   # 2행 3열의 랜덤 텐서, 자료형 float32



tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[ 0.2255,  0.3976, -1.7874],
        [-1.0047, -0.8983, -0.1386]]) 

